[package]
name = "countdown"
version = "0.3.0-alpha"
edition = "2021"

[dependencies]
chrono = "0.4.35"
chrono-tz = "0.8.6"
clap = { version = "4.5.3", features = ["derive"] }
crossterm = "0.27.0"
iana-time-zone = "0.1.60"
